### ISSUE TITLE
Unknown command received when create a new block

### ISSUE THREAD

**Issue by sobreira** [MrYsLab/s2-pi#5] opened 2018-11-10 00:42 UTC
Hi Alan,
I am trying to include more devices in this extension, however I am stuck in 2 things:

1.  When I include a new blocks, I receive the following error message when block is selected: (Unknown command received XXX).
I tried to copy a "working" blocks just changing the names and variables names and the error message is the same - file is attached with this scenario.
Have you seen this issue before?

2. Is it possible to include another block for input new devices? Like a LDR, LM35, potentiometer (both are analogic - so I am trying to use a MCP3008 to get up to 8 analogic port - in Python worked fine.
Or Digital device like ds18s20 or DHT11/22.
I have tried several aproaches without success.

In Python this simple code works fine and I tried to incorporate it  - no success at all
`from gpiozero import MCP3008`
`pin = 2`
`pot = MCP3008(pin)`
`while True:`
`	print("%.2f" % round(pot.value)`

[s2-pi-master.zip](https://github.com/MrYsLab/s2-pi/files/2567869/s2-pi-master.zip)

Thanks!

**Comment by MrYsLab** [comment] 2018-11-10 15:07
I may not be understanding what you are describing in 1. above. Please let me know if what I describe next is what caused a problem for you.

1. I uninstalled s2-pi from my RPi using sudo pip3 uninstall s2-pi.
2. I unzipped s2-pi-master.zip that you supplied above and installed on to the RPi.
3. I started s2-pi and loaded the blocks with servo2 into Scratch.
4. I connected to the server.
5. I executed the servo block and the servo2 block.
Here are some screenshots:
![screenshot from 2018-11-10 09-44-29](https://user-images.githubusercontent.com/5189838/48302727-49f52a80-e4ce-11e8-9b5b-9376ac47cf28.png)
![screenshot from 2018-11-10 09-45-13](https://user-images.githubusercontent.com/5189838/48302730-5083a200-e4ce-11e8-8874-1caf266f9b9d.png)

As you can see I am getting no errors.

I then removed your modified version and reinstalled s2-pi from pip and reran your script with the added servo2 block. This did fail as I would expect.

![screenshot from 2018-11-10 09-47-36](https://user-images.githubusercontent.com/5189838/48302750-7dd05000-e4ce-11e8-80c7-090c1bf01612.png)

Did you remove the original version of s2-pi?

If you did and are still seeing the error, what character encoding are you using on your RPi?
You can view and select from raspi-config.
![screenshot from 2018-11-10 09-55-48](https://user-images.githubusercontent.com/5189838/48303455-64340600-e4d8-11e8-824d-2e37cc3ccdba.png)

I am using UTF-8:
![screenshot from 2018-11-10 09-59-37](https://user-images.githubusercontent.com/5189838/48302817-90975480-e4cf-11e8-9025-ede9edbb520a.png)

You may have one of the Brazilian locales selected such as shown below:
![screenshot from 2018-11-10 09-58-55](https://user-images.githubusercontent.com/5189838/48302830-bb81a880-e4cf-11e8-8731-35973582a803.png)

If you already have a UTF-8 encoding selected then I am not sure what the problem might be.

To answer question #2, yes, you should be able to add as many blocks as you wish. If you are able to support the hardware for the block, you should be able to link the block to the Python support code for the device as you did for the Servo. 

Let me know if you are still having problems for either question.

Thanks.

**Comment by sobreira** [comment] 2018-11-10 22:27
Thanks a lot for your prompt reply.
I did several reinstalation this should be the case.
I will try again.

Thanks one more time.

**Comment by MrYsLab** [comment] 2018-11-10 23:16
If you still have issues, don't hesitate to ask for help.

One of the things you can do to make sure you have the correct version loaded is to change the version string in setup.py to give your version a unique number: https://github.com/MrYsLab/s2-pi/blob/278e0775bb3d93729df3ad876d94d054c26924ec/setup.py#L15

**Comment by sobreira** [comment] 2018-11-12 01:34
thanks for the hint

**Comment by sobreira** [comment] 2018-11-13 09:57
Thanks.
Your advices solve the issue.
I could get the reading sensor back to scratch block

Now I am strugling in another thing - Hope you can guide me again :)

The program freezes during execution - reading sensors.
Firstly I just use the code: (for MCP3008 but I also tested for DHT11)
`print("%.2f" % round(mcp.value,2))`
After some reading Scratch crashes.

The same happen when I get back the reading data to Scratch
Data are transfered and after some while Scratch freezes too even not printed the result on screen.

Do you think it's related to some buffer/memory, etc... issue?
Or even my changes....

Thanks!
[s2-pi-master.zip](https://github.com/MrYsLab/s2-pi/files/2575660/s2-pi-master.zip)

**Comment by MrYsLab** [comment] 2018-11-13 13:53
If you do not use the MCP3008 block in your Scratch program, do things still crash?

In your Scratch program, when you use the MCP3008 block how often are you calling it? What I mean is, do you have a "wait" block in the loop? If you don't have a wait block, I would add one. Try a large number like 1 second at first and see if it still crashes.

One thing I noticed in the javascript file, you probably want to use parseFloat and not parseInt for the MCP3008. I don't think that is causing the crash, but if you want a floating point number that will do the correct string conversion.

**Comment by sobreira** [comment] 2018-11-16 03:06
I have made several tests, also with DH11 and the situation is basically the same.
I registred (creating a list in Scratch) that the system returns ~220 registries before crash even if with Wait block (1s).

Looks that Scratch side sends more comands that can be processed at the Raspberry side, flooding raspberry until the combination crashes and a reboot is needed.

In some tests, even after I stopped Scratch the terminal continues processing showing the pin status - kind of queue and in other case only rebooting

This afternoon I decided to switch the module I was using and I find one much better, I could run the system for more the 1000 registries without any issue.
Not system not crash but the conection to server fall and I receive the following message:

![image](https://user-images.githubusercontent.com/5200448/48595393-995ab100-e93b-11e8-814e-d85a0bfb246e.png)

Have you seen it before?

Thanks!

**Comment by MrYsLab** [comment] 2018-11-16 13:08
I think the error you are seeing may be caused by having remote GPIO enabled. s2-pi does not use this feature. To disable it, [this link](https://gpiozero.readthedocs.io/en/stable/remote_gpio.html#enable-remote-connections) should help.

The s2-pi code uses port 9000 and not 8888, so the error message is confusing. Do you have anything else running that might be using the 8888 port? In any case, I would think disabling remote GPIO should solve this issue.

**Comment by MrYsLab** [comment] 2018-11-17 16:09
Since you have gotten past the original issue, I am going to close this issue. Even though it is closed, I will see any comments you add here. If we need to, we can always re-open this issue.

Thanks.

**Closed as completed by MrYsLab** 2018-11-17 16:09 UTC
